-- 024_EncryptOidcClientSecret.sql
--
-- ADMIN-001 (PREPUB-2026-05-09): the oidc_client_secret column on
-- tenant_auth_config previously persisted plaintext. The schema itself stays
-- unchanged (TEXT column); the encryption transform happens in application
-- code via Microsoft.AspNetCore.DataProtection — keeping the data-protection
-- key out of any SQL surface.
--
-- The actual one-shot wrap of legacy rows is performed by
-- OidcClientSecretEncryptionMigrator (IHostedService) at process startup.
-- The migrator:
--   1. SELECTs every row whose oidc_client_secret is non-null,
--   2. tries Unprotect(value) — if it succeeds, the row is already encrypted,
--      so it is skipped (idempotent re-runs across deploys),
--   3. otherwise treats the value as legacy plaintext, calls Protect(value),
--      and UPDATEs the row.
--
-- This SQL file exists ONLY so the platform's migration ledger
-- (`_migrations` table maintained by DatabaseMigrationService) records that
-- the admin-001 remediation step ran. The SELECT 1 statement is a no-op.
SELECT 1;
