apiVersion: v1
kind: ResourceQuota
metadata:
  name: r55-data-quota
  namespace: r55-data
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 12Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: r55-asterisk-quota
  namespace: r55-asterisk
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 6Gi
    limits.cpu: "16"
    limits.memory: 16Gi
    pods: "15"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: r55-platform-quota
  namespace: r55-platform
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "18"
    limits.memory: 18Gi
    pods: "15"
