using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;

namespace Verbara.Platform.Llm;

/// <summary>
/// Owns the <c>verbara.platform.llm</c> <see cref="Meter"/> and all instruments
/// (counters + latency histogram) emitted by the LLM path.
/// </summary>
/// <remarks>
/// Follow the house pattern from <c>JwtTokenService</c>: constructed via an
/// optional <see cref="IMeterFactory"/> (production DI path) with a plain
/// <c>new Meter(...)</c> fallback so unit-test constructors that omit the factory
/// still compile and run.
/// </remarks>
internal sealed partial class LlmMetrics : IDisposable
{
    /// <summary>Name of the <see cref="Meter"/> registered with OpenTelemetry.</summary>
    internal const string MeterName = "verbara.platform.llm";

    private readonly Meter _meter;

    internal readonly Counter<long> Requests;
    internal readonly Counter<long> Errors;
    internal readonly Histogram<double> RequestLatency;
    internal readonly Counter<long> TokensIn;
    internal readonly Counter<long> TokensOut;

    internal LlmMetrics(IMeterFactory? meterFactory)
    {
        _meter = meterFactory is null ? new Meter(MeterName) : meterFactory.Create(MeterName);

        Requests = _meter.CreateCounter<long>(
            "llm.requests",
            description: "Total LLM completion requests dispatched.");
        Errors = _meter.CreateCounter<long>(
            "llm.errors",
            description: "LLM completion requests that ended with an HTTP or deserialization error.");
        RequestLatency = _meter.CreateHistogram<double>(
            "llm.request.latency",
            unit: "ms",
            description: "End-to-end wall-clock latency of each LLM completion request in milliseconds.");
        TokensIn = _meter.CreateCounter<long>(
            "llm.tokens.in",
            description: "Prompt tokens consumed by LLM requests (as reported by the provider).");
        TokensOut = _meter.CreateCounter<long>(
            "llm.tokens.out",
            description: "Completion tokens generated by LLM requests (as reported by the provider).");
    }

    // ─── Structured log events (EventIds 6300-6301; 6302+ reserved for later P2b tasks, e.g. over-budget in E3) ───

    [LoggerMessage(EventId = 6300, Level = LogLevel.Warning,
        Message = "LLM provider call failed after {ElapsedMs:F1} ms.")]
    internal static partial void LogProviderFailure(ILogger logger, double elapsedMs, Exception exception);

    [LoggerMessage(EventId = 6301, Level = LogLevel.Debug,
        Message = "LLM provider returned empty or null content; caller will receive an empty string.")]
    internal static partial void LogEmptyContent(ILogger logger);

    public void Dispose() => _meter.Dispose();
}
