using System.Text.Json.Serialization;
using Asterisk.Platform.Api.Endpoints;
using Asterisk.Platform.Conversations;
using Asterisk.Platform.Core;
using Asterisk.Platform.Flows;
using Asterisk.Platform.Identity;
using Asterisk.Platform.Queues;
using Asterisk.Platform.Switchboard;

namespace Asterisk.Platform.Api.Serialization;

[JsonSerializable(typeof(PagedResult<User>))]
[JsonSerializable(typeof(PagedResult<Queue>))]
[JsonSerializable(typeof(PagedResult<Agent>))]
[JsonSerializable(typeof(PagedResult<Team>))]
[JsonSerializable(typeof(PagedResult<Conversation>))]
[JsonSerializable(typeof(PagedResult<Contact>))]
[JsonSerializable(typeof(PagedResult<ApiKey>))]
[JsonSerializable(typeof(PagedResult<CampaignSummaryDto>))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(Queue))]
[JsonSerializable(typeof(Agent))]
[JsonSerializable(typeof(Team))]
[JsonSerializable(typeof(Conversation))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Contact))]
[JsonSerializable(typeof(FlowDefinition))]
[JsonSerializable(typeof(ApiKey))]
[JsonSerializable(typeof(OwnershipResult))]
[JsonSerializable(typeof(ConversationAssignedEvent))]
[JsonSerializable(typeof(ConversationMessageEvent))]
[JsonSerializable(typeof(ConversationStateChangedEvent))]
[JsonSerializable(typeof(AgentStateChangedEvent))]
[JsonSerializable(typeof(CampaignStatusChangedEvent))]
[JsonSerializable(typeof(CampaignMetricsUpdatedEvent))]
[JsonSerializable(typeof(CampaignDispositionSubmittedEvent))]
[JsonSerializable(typeof(CampaignSummaryDto))]
[JsonSerializable(typeof(CampaignDetailDto))]
[JsonSerializable(typeof(ScheduleDayDto))]
[JsonSerializable(typeof(ContactListDto))]
[JsonSerializable(typeof(List<ContactListDto>))]
[JsonSerializable(typeof(CreateContactListRequest))]
[JsonSerializable(typeof(ImportContactsRequest))]
[JsonSerializable(typeof(ImportResultDto))]
[JsonSerializable(typeof(PagedResult<Contact>))]
[JsonSerializable(typeof(DispositionCodeDto))]
[JsonSerializable(typeof(List<DispositionCodeDto>))]
[JsonSerializable(typeof(CreateDispositionCodeRequest))]
[JsonSerializable(typeof(UpdateDispositionCodeRequest))]
[JsonSerializable(typeof(CampaignMetricsDto))]
[JsonSerializable(typeof(List<CampaignMetricsDto>))]
[JsonSerializable(typeof(WrapUpRequest))]
[JsonSerializable(typeof(DashboardDto))]
[JsonSerializable(typeof(DashboardKpisDto))]
[JsonSerializable(typeof(TrendPointDto))]
[JsonSerializable(typeof(TrendPointDto[]))]
[JsonSerializable(typeof(ChannelDistributionDto))]
[JsonSerializable(typeof(ChannelDistributionDto[]))]
[JsonSerializable(typeof(CdrRowDto))]
[JsonSerializable(typeof(List<CdrRowDto>))]
[JsonSerializable(typeof(CdrDetailDto))]
[JsonSerializable(typeof(CdrTimelineEventDto))]
[JsonSerializable(typeof(CdrTimelineEventDto[]))]
[JsonSerializable(typeof(CdrQaSummaryDto))]
[JsonSerializable(typeof(QaRowDto))]
[JsonSerializable(typeof(List<QaRowDto>))]
[JsonSerializable(typeof(QaDetailDto))]
[JsonSerializable(typeof(QaCriterionDto))]
[JsonSerializable(typeof(QaCriterionDto[]))]
[JsonSerializable(typeof(ComplianceViolationDto))]
[JsonSerializable(typeof(ComplianceViolationDto[]))]
[JsonSerializable(typeof(TopicDto))]
[JsonSerializable(typeof(TopicDto[]))]
[JsonSerializable(typeof(IntervalDto))]
[JsonSerializable(typeof(List<IntervalDto>))]
[JsonSerializable(typeof(TrunkDto))]
[JsonSerializable(typeof(List<TrunkDto>))]
[JsonSerializable(typeof(CreateTrunkRequest))]
[JsonSerializable(typeof(UpdateTrunkRequest))]
[JsonSerializable(typeof(OutboundRouteDto))]
[JsonSerializable(typeof(List<OutboundRouteDto>))]
[JsonSerializable(typeof(CreateOutboundRouteRequest))]
[JsonSerializable(typeof(UpdateOutboundRouteRequest))]
[JsonSerializable(typeof(long[]))]
// DNC Lists
[JsonSerializable(typeof(DncListDto))]
[JsonSerializable(typeof(List<DncListDto>))]
[JsonSerializable(typeof(CreateDncListRequest))]
[JsonSerializable(typeof(UpdateDncListRequest))]
[JsonSerializable(typeof(AddDncEntryRequest))]
[JsonSerializable(typeof(DncEntryDto))]
[JsonSerializable(typeof(List<DncEntryDto>))]
[JsonSerializable(typeof(DncImportResultDto))]
[JsonSerializable(typeof(DncCheckResultDto))]
// Caller ID Pools
[JsonSerializable(typeof(CallerIdPoolDto))]
[JsonSerializable(typeof(List<CallerIdPoolDto>))]
[JsonSerializable(typeof(CreateCallerIdPoolRequest))]
[JsonSerializable(typeof(UpdateCallerIdPoolRequest))]
[JsonSerializable(typeof(AddCallerIdEntryRequest))]
[JsonSerializable(typeof(CallerIdEntryDto))]
[JsonSerializable(typeof(List<CallerIdEntryDto>))]
// Holiday Calendars
[JsonSerializable(typeof(HolidayCalendarDto))]
[JsonSerializable(typeof(List<HolidayCalendarDto>))]
[JsonSerializable(typeof(CreateHolidayCalendarRequest))]
[JsonSerializable(typeof(UpdateHolidayCalendarRequest))]
[JsonSerializable(typeof(AddHolidayRequest))]
[JsonSerializable(typeof(HolidayDto))]
[JsonSerializable(typeof(List<HolidayDto>))]
// Recordings
[JsonSerializable(typeof(RecordingMetadataDto))]
// Queue Members
[JsonSerializable(typeof(AddQueueMemberRequest))]
// Dialer Settings
[JsonSerializable(typeof(DialerSettingsDto))]
[JsonSerializable(typeof(UpdateDialerSettingsRequest))]
// Agent Assist
[JsonSerializable(typeof(KeywordRuleDto))]
[JsonSerializable(typeof(KeywordRuleDto[]))]
[JsonSerializable(typeof(ComplianceRuleDto))]
[JsonSerializable(typeof(ComplianceRuleDto[]))]
[JsonSerializable(typeof(AgentAssistConfigSnapshot))]
[JsonSerializable(typeof(AgentAssistSessionDto))]
[JsonSerializable(typeof(SuggestionLogRowDto))]
[JsonSerializable(typeof(SuggestionLogRowDto[]))]
[JsonSerializable(typeof(ComplianceAlertRowDto))]
[JsonSerializable(typeof(ComplianceAlertRowDto[]))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
internal partial class ApiJsonContext : JsonSerializerContext;
