using System.Text.Json.Serialization;
using Asterisk.Platform.Api.Endpoints;
using Asterisk.Platform.Api.Endpoints.Shared;
using Asterisk.Platform.Api.Services;
using Asterisk.Platform.Bot;
using Asterisk.Platform.Billing;
using Asterisk.Platform.Conversations;
using Asterisk.Platform.Core;
using Asterisk.Platform.Core.Email;
using Asterisk.Platform.Core.Reports;
using Asterisk.Platform.Core.Webhooks;
using Asterisk.Platform.Flows;
using Asterisk.Platform.Identity;
using Asterisk.Platform.Queues;
using Asterisk.Platform.Switchboard;
using Microsoft.AspNetCore.Mvc;

namespace Asterisk.Platform.Api.Serialization;

[JsonSerializable(typeof(PagedResult<User>))]
[JsonSerializable(typeof(PagedResult<Queue>))]
[JsonSerializable(typeof(PagedResult<Agent>))]
[JsonSerializable(typeof(PagedResult<Team>))]
[JsonSerializable(typeof(PagedResult<TeamDto>))]
[JsonSerializable(typeof(TeamDto))]
[JsonSerializable(typeof(PagedResult<UserDto>))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(PagedResult<QueueDto>))]
[JsonSerializable(typeof(QueueDto))]
[JsonSerializable(typeof(ArticleDto[]))]
[JsonSerializable(typeof(ArticleDto))]
[JsonSerializable(typeof(ScheduledReportDto[]))]
[JsonSerializable(typeof(ScheduledReportDto))]
[JsonSerializable(typeof(SurveyDto[]))]
[JsonSerializable(typeof(SurveyDto))]
[JsonSerializable(typeof(PagedResult<Conversation>))]
[JsonSerializable(typeof(PagedResult<Contact>))]
[JsonSerializable(typeof(PagedResult<ApiKey>))]
[JsonSerializable(typeof(PagedResult<CampaignSummaryDto>))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(Queue))]
[JsonSerializable(typeof(Agent))]
[JsonSerializable(typeof(Team))]
[JsonSerializable(typeof(Conversation))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Contact))]
[JsonSerializable(typeof(FlowDefinition))]
[JsonSerializable(typeof(ApiKey))]
[JsonSerializable(typeof(OwnershipResult))]
[JsonSerializable(typeof(ConversationAssignedEvent))]
[JsonSerializable(typeof(ConversationMessageEvent))]
[JsonSerializable(typeof(ConversationStateChangedEvent))]
[JsonSerializable(typeof(AgentStateChangedEvent))]
[JsonSerializable(typeof(CampaignStatusChangedEvent))]
[JsonSerializable(typeof(CampaignMetricsUpdatedEvent))]
[JsonSerializable(typeof(CampaignDispositionSubmittedEvent))]
// SSE: Switchboard & Queue events
[JsonSerializable(typeof(ConversationOfferedEvent))]
[JsonSerializable(typeof(ConversationOfferExpiredEvent))]
[JsonSerializable(typeof(ConversationAbandonedEvent))]
[JsonSerializable(typeof(AgentCapacityChangedEvent))]
// SSE: Agent Assist events
[JsonSerializable(typeof(AgentAssistSuggestionEvent))]
[JsonSerializable(typeof(AgentAssistSentimentEvent))]
[JsonSerializable(typeof(AgentAssistComplianceAlertEvent))]
[JsonSerializable(typeof(AgentAssistTranscriptEvent))]
// SSE: Notification events
[JsonSerializable(typeof(NotificationEvent))]
[JsonSerializable(typeof(CampaignSummaryDto))]
[JsonSerializable(typeof(CampaignDetailDto))]
[JsonSerializable(typeof(ScheduleDayDto))]
[JsonSerializable(typeof(ContactListDto))]
[JsonSerializable(typeof(List<ContactListDto>))]
[JsonSerializable(typeof(CreateContactListRequest))]
[JsonSerializable(typeof(ImportContactsRequest))]
[JsonSerializable(typeof(ImportResultDto))]
[JsonSerializable(typeof(PagedResult<Contact>))]
[JsonSerializable(typeof(DispositionCodeDto))]
[JsonSerializable(typeof(List<DispositionCodeDto>))]
[JsonSerializable(typeof(CreateDispositionCodeRequest))]
[JsonSerializable(typeof(UpdateDispositionCodeRequest))]
[JsonSerializable(typeof(CampaignMetricsDto))]
[JsonSerializable(typeof(List<CampaignMetricsDto>))]
[JsonSerializable(typeof(WrapUpRequest))]
[JsonSerializable(typeof(CreateConversationRequest))]
[JsonSerializable(typeof(DashboardDto))]
[JsonSerializable(typeof(DashboardKpisDto))]
[JsonSerializable(typeof(TrendPointDto))]
[JsonSerializable(typeof(TrendPointDto[]))]
[JsonSerializable(typeof(ChannelDistributionDto))]
[JsonSerializable(typeof(ChannelDistributionDto[]))]
[JsonSerializable(typeof(CdrRowDto))]
[JsonSerializable(typeof(List<CdrRowDto>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(CdrDetailDto))]
[JsonSerializable(typeof(CdrTimelineEventDto))]
[JsonSerializable(typeof(CdrTimelineEventDto[]))]
[JsonSerializable(typeof(CdrQaSummaryDto))]
[JsonSerializable(typeof(QaRowDto))]
[JsonSerializable(typeof(List<QaRowDto>))]
[JsonSerializable(typeof(QaDetailDto))]
[JsonSerializable(typeof(QaCriterionDto))]
[JsonSerializable(typeof(QaCriterionDto[]))]
[JsonSerializable(typeof(ComplianceViolationDto))]
[JsonSerializable(typeof(ComplianceViolationDto[]))]
[JsonSerializable(typeof(TopicDto))]
[JsonSerializable(typeof(TopicDto[]))]
[JsonSerializable(typeof(IntervalDto))]
[JsonSerializable(typeof(List<IntervalDto>))]
[JsonSerializable(typeof(AgentIntervalDto))]
[JsonSerializable(typeof(List<AgentIntervalDto>))]
[JsonSerializable(typeof(LiveStateDto))]
[JsonSerializable(typeof(List<LiveStateDto>))]
[JsonSerializable(typeof(CurrentIntervalDto))]
[JsonSerializable(typeof(TrunkDto))]
[JsonSerializable(typeof(List<TrunkDto>))]
[JsonSerializable(typeof(CreateTrunkRequest))]
[JsonSerializable(typeof(UpdateTrunkRequest))]
[JsonSerializable(typeof(OutboundRouteDto))]
[JsonSerializable(typeof(List<OutboundRouteDto>))]
[JsonSerializable(typeof(CreateOutboundRouteRequest))]
[JsonSerializable(typeof(UpdateOutboundRouteRequest))]
[JsonSerializable(typeof(long[]))]
// DNC Lists
[JsonSerializable(typeof(DncListDto))]
[JsonSerializable(typeof(List<DncListDto>))]
[JsonSerializable(typeof(CreateDncListRequest))]
[JsonSerializable(typeof(UpdateDncListRequest))]
[JsonSerializable(typeof(AddDncEntryRequest))]
[JsonSerializable(typeof(DncEntryDto))]
[JsonSerializable(typeof(List<DncEntryDto>))]
[JsonSerializable(typeof(DncImportResultDto))]
[JsonSerializable(typeof(DncCheckResultDto))]
// Caller ID Pools
[JsonSerializable(typeof(CallerIdPoolDto))]
[JsonSerializable(typeof(List<CallerIdPoolDto>))]
[JsonSerializable(typeof(CreateCallerIdPoolRequest))]
[JsonSerializable(typeof(UpdateCallerIdPoolRequest))]
[JsonSerializable(typeof(AddCallerIdEntryRequest))]
[JsonSerializable(typeof(CallerIdEntryDto))]
[JsonSerializable(typeof(List<CallerIdEntryDto>))]
// Holiday Calendars
[JsonSerializable(typeof(HolidayCalendarDto))]
[JsonSerializable(typeof(List<HolidayCalendarDto>))]
[JsonSerializable(typeof(CreateHolidayCalendarRequest))]
[JsonSerializable(typeof(UpdateHolidayCalendarRequest))]
[JsonSerializable(typeof(AddHolidayRequest))]
[JsonSerializable(typeof(HolidayDto))]
[JsonSerializable(typeof(List<HolidayDto>))]
// Recordings
[JsonSerializable(typeof(RecordingMetadataDto))]
// Queue Members
[JsonSerializable(typeof(AddQueueMemberRequest))]
// Dialer Settings
[JsonSerializable(typeof(DialerSettingsDto))]
[JsonSerializable(typeof(UpdateDialerSettingsRequest))]
// Skills
[JsonSerializable(typeof(SkillDto))]
[JsonSerializable(typeof(List<SkillDto>))]
[JsonSerializable(typeof(AgentSkillDto))]
[JsonSerializable(typeof(List<AgentSkillDto>))]
[JsonSerializable(typeof(CreateSkillRequest))]
[JsonSerializable(typeof(UpsertSkillRequest))]
[JsonSerializable(typeof(AssignSkillRequest))]
// Call Attempts
[JsonSerializable(typeof(UpdateCallAttemptDispositionRequest))]
// Callbacks
[JsonSerializable(typeof(CallbackDto))]
[JsonSerializable(typeof(List<CallbackDto>))]
[JsonSerializable(typeof(CreateCallbackRequest))]
// Realtime Endpoint Profiles
[JsonSerializable(typeof(EndpointProfileDto))]
[JsonSerializable(typeof(List<EndpointProfileDto>))]
[JsonSerializable(typeof(CreateEndpointProfileRequest))]
[JsonSerializable(typeof(UpdateEndpointProfileRequest))]
// Management Cluster
[JsonSerializable(typeof(MgmtClusterStatusDto))]
[JsonSerializable(typeof(MgmtClusterNodeDto))]
[JsonSerializable(typeof(List<MgmtClusterNodeDto>))]
[JsonSerializable(typeof(MgmtDrainNodeRequest))]
[JsonSerializable(typeof(MgmtDrainStatusDto))]
[JsonSerializable(typeof(CreateNodeRequest))]
[JsonSerializable(typeof(UpdateNodeRequest))]
[JsonSerializable(typeof(MgmtInstanceDto))]
[JsonSerializable(typeof(List<MgmtInstanceDto>))]
// Impersonation
[JsonSerializable(typeof(ImpersonateRequest))]
[JsonSerializable(typeof(ImpersonateResponse))]
// Management Tenants
[JsonSerializable(typeof(MgmtTenantDto))]
[JsonSerializable(typeof(List<MgmtTenantDto>))]
[JsonSerializable(typeof(CreateMgmtTenantRequest))]
[JsonSerializable(typeof(UpdateMgmtTenantRequest))]
// Partner Customers
[JsonSerializable(typeof(PartnerCustomerDto))]
[JsonSerializable(typeof(List<PartnerCustomerDto>))]
[JsonSerializable(typeof(CreatePartnerCustomerRequest))]
[JsonSerializable(typeof(UpdatePartnerCustomerRequest))]
// Partner Billing
[JsonSerializable(typeof(PartnerGenerateInvoiceResponse))]
[JsonSerializable(typeof(PartnerRevenueSnapshotDto))]
// Partner Revenue
[JsonSerializable(typeof(PartnerRevenueSummaryDto))]
[JsonSerializable(typeof(PartnerRevenueDetailDto))]
[JsonSerializable(typeof(List<PartnerRevenueDetailDto>))]
// Management API Keys
[JsonSerializable(typeof(MgmtApiKeyDto))]
[JsonSerializable(typeof(List<MgmtApiKeyDto>))]
[JsonSerializable(typeof(CreateMgmtApiKeyRequest))]
[JsonSerializable(typeof(CreateMgmtApiKeyResponse))]
// Setup
[JsonSerializable(typeof(SetupRequest))]
[JsonSerializable(typeof(SetupResponse))]
// System Settings
[JsonSerializable(typeof(SystemSettingsRequest))]
// Auth
[JsonSerializable(typeof(TokenResponse))]
[JsonSerializable(typeof(TokenUserDto))]
// Agent Assist
[JsonSerializable(typeof(KeywordRuleDto))]
[JsonSerializable(typeof(KeywordRuleDto[]))]
[JsonSerializable(typeof(ComplianceRuleDto))]
[JsonSerializable(typeof(ComplianceRuleDto[]))]
[JsonSerializable(typeof(AgentAssistConfigSnapshot))]
[JsonSerializable(typeof(AgentAssistSessionDto))]
[JsonSerializable(typeof(SuggestionLogRowDto))]
[JsonSerializable(typeof(SuggestionLogRowDto[]))]
[JsonSerializable(typeof(ComplianceAlertRowDto))]
[JsonSerializable(typeof(ComplianceAlertRowDto[]))]
// Cases
[JsonSerializable(typeof(Case))]
[JsonSerializable(typeof(PagedResult<Case>))]
[JsonSerializable(typeof(CreateCaseRequest))]
[JsonSerializable(typeof(UpdateCaseRequest))]
// Bot Analytics
[JsonSerializable(typeof(BotAnalyticsSummary))]
// Bots
[JsonSerializable(typeof(BotDto))]
[JsonSerializable(typeof(BotDto[]))]
[JsonSerializable(typeof(CreateBotRequest))]
[JsonSerializable(typeof(UpdateBotRequest))]
// Shared response DTOs
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(ErrorDetailResponse))]
[JsonSerializable(typeof(MessageResponse))]
[JsonSerializable(typeof(StatusUpdateResponse))]
[JsonSerializable(typeof(PagedDataResponse<CdrRowDto>))]
[JsonSerializable(typeof(PagedDataResponse<QaRowDto>))]
// Auth
[JsonSerializable(typeof(RevokedSessionsResponse))]
[JsonSerializable(typeof(MfaChallengeResponse))]
[JsonSerializable(typeof(MfaEnrollmentRequiredResponse))]
[JsonSerializable(typeof(MfaStepUpRequiredResponse))]
[JsonSerializable(typeof(PasswordResetMfaRequiredResponse))]
[JsonSerializable(typeof(AuthEventDetail))]
[JsonSerializable(typeof(UserSessionDto))]
[JsonSerializable(typeof(UserSessionDto[]))]
[JsonSerializable(typeof(ActiveSession))]
[JsonSerializable(typeof(IReadOnlyList<ActiveSession>))]
[JsonSerializable(typeof(RegenerateRecoveryCodesRequest))]
[JsonSerializable(typeof(RecoveryCodesResponse))]
[JsonSerializable(typeof(PasswordPolicyDto))]
// RBAC
[JsonSerializable(typeof(PermissionGroupDto))]
[JsonSerializable(typeof(List<PermissionGroupDto>))]
[JsonSerializable(typeof(UserPermissionsDto))]
[JsonSerializable(typeof(PermissionDefinition))]
[JsonSerializable(typeof(List<PermissionDefinition>))]
// Channel Config
[JsonSerializable(typeof(ChannelStatusDto))]
[JsonSerializable(typeof(ChannelTestResponse))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, bool>))]
// Management System
[JsonSerializable(typeof(SystemInfoDto))]
[JsonSerializable(typeof(LicenseInfoDto))]
[JsonSerializable(typeof(SystemSettingsDto))]
// GDPR
[JsonSerializable(typeof(GdprExportRequest))]
[JsonSerializable(typeof(GdprPurgeRequest))]
[JsonSerializable(typeof(GdprExportResult))]
[JsonSerializable(typeof(GdprSubjectInfo))]
[JsonSerializable(typeof(GdprExportData))]
[JsonSerializable(typeof(GdprConversationRecord))]
[JsonSerializable(typeof(GdprRecordingRecord))]
[JsonSerializable(typeof(GdprCallDetailRecord))]
[JsonSerializable(typeof(GdprSurveyResponseRecord))]
[JsonSerializable(typeof(GdprAuditRecord))]
[JsonSerializable(typeof(List<GdprConversationRecord>))]
[JsonSerializable(typeof(List<GdprRecordingRecord>))]
[JsonSerializable(typeof(List<GdprCallDetailRecord>))]
[JsonSerializable(typeof(List<GdprSurveyResponseRecord>))]
[JsonSerializable(typeof(List<GdprAuditRecord>))]
[JsonSerializable(typeof(PurgeResult))]
[JsonSerializable(typeof(PagedResult<PurgeEntry>))]
[JsonSerializable(typeof(PurgeEntry))]
[JsonSerializable(typeof(RetentionPolicyDto))]
[JsonSerializable(typeof(UpdateRetentionPolicyRequest))]
[JsonSerializable(typeof(TenantRetentionPolicy))]
[JsonSerializable(typeof(Dictionary<string, int>))]
// TenantSettings Facade
[JsonSerializable(typeof(TenantSettingsDto))]
[JsonSerializable(typeof(DunningStatusDto))]
[JsonSerializable(typeof(DunningRecordDto))]
[JsonSerializable(typeof(TenantPlan))]
[JsonSerializable(typeof(PlanFeature))]
[JsonSerializable(typeof(PaymentStatus))]
[JsonSerializable(typeof(IReadOnlyList<PlanFeature>))]
[JsonSerializable(typeof(UpdateTenantSettingsRequest))]
[JsonSerializable(typeof(OperationalSettingsDto))]
[JsonSerializable(typeof(AuthSettingsDto))]
[JsonSerializable(typeof(QuotaSettingsDto))]
[JsonSerializable(typeof(RetentionSettingsDto))]
[JsonSerializable(typeof(UpdateOperationalSettingsDto))]
[JsonSerializable(typeof(UpdateAuthSettingsDto))]
[JsonSerializable(typeof(UpdateQuotaSettingsDto))]
[JsonSerializable(typeof(UpdateRetentionSettingsDto))]
[JsonSerializable(typeof(BrandingSettingsDto))]
[JsonSerializable(typeof(UpdateBrandingSettingsDto))]
[JsonSerializable(typeof(UpdateManagementBrandingSettingsDto))]
[JsonSerializable(typeof(ManagementUpdateTenantSettingsRequest))]
// Webhooks
[JsonSerializable(typeof(WebhookSubscription))]
[JsonSerializable(typeof(List<WebhookSubscription>))]
[JsonSerializable(typeof(WebhookDelivery))]
[JsonSerializable(typeof(List<WebhookDelivery>))]
[JsonSerializable(typeof(PagedResult<WebhookDelivery>))]
[JsonSerializable(typeof(WebhookEventPayload))]
[JsonSerializable(typeof(WebhookDeliveryStatus))]
[JsonSerializable(typeof(CreateWebhookSubscriptionRequest))]
[JsonSerializable(typeof(UpdateWebhookSubscriptionRequest))]
[JsonSerializable(typeof(WebhookEventTypeDto))]
[JsonSerializable(typeof(List<WebhookEventTypeDto>))]
// Notifications
[JsonSerializable(typeof(NotificationEndpoints.NotificationDto))]
[JsonSerializable(typeof(List<NotificationEndpoints.NotificationDto>))]
[JsonSerializable(typeof(NotificationEndpoints.UnreadCountDto))]
// Branding (public)
[JsonSerializable(typeof(BrandingEndpoints.PublicBrandingDto))]
// Supervisor Digital
[JsonSerializable(typeof(SupervisorCloseRequest))]
[JsonSerializable(typeof(CoachingNoteRequest))]
// Canned Responses
[JsonSerializable(typeof(CannedResponseEndpoints.CreateCannedResponseRequest))]
[JsonSerializable(typeof(CannedResponseEndpoints.UpdateCannedResponseRequest))]
[JsonSerializable(typeof(CannedResponseEndpoints.CannedResponseDto))]
[JsonSerializable(typeof(List<CannedResponseEndpoints.CannedResponseDto>))]
// WebChat
[JsonSerializable(typeof(WebChatEndpoints.CreateSessionRequest))]
[JsonSerializable(typeof(WebChatEndpoints.CreateSessionResponse))]
[JsonSerializable(typeof(WebChatEndpoints.WebChatMessageRequest))]
// Onboarding
[JsonSerializable(typeof(OnboardingStatusDto))]
[JsonSerializable(typeof(ChecklistItemDto))]
[JsonSerializable(typeof(List<ChecklistItemDto>))]
[JsonSerializable(typeof(ApplyTemplateRequest))]
// AOT: ProblemDetails, Email, Reports
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(EmailMessage))]
[JsonSerializable(typeof(EmailRecipient))]
[JsonSerializable(typeof(EmailAttachment))]
[JsonSerializable(typeof(ReportData))]
[JsonSerializable(typeof(ReportDataRow))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UseStringEnumConverter = true)]
internal partial class ApiJsonContext : JsonSerializerContext;
