[from-trunk]
exten => _X.,1,Stasis(asterisk_platform,inbound,${EXTEN})
 same => n,Hangup()

[from-internal]
exten => _X.,1,Stasis(asterisk_platform,internal,${EXTEN})
 same => n,Hangup()

[default]
exten => _X.,1,Stasis(asterisk_platform)
 same => n,Hangup()

[agentassist]
exten => audiosocket,1,AudioSocket(${AUDIOSOCKET_UUID},${AUDIOSOCKET_HOST}:9092)
 same => n,Hangup()
