[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038

[platform]
secret = platform_secret
read = system,call,agent,user,config,originate,reporting,command
write = system,call,agent,user,config,originate,command
deny = 0.0.0.0/0.0.0.0
permit = 0.0.0.0/0.0.0.0
