[res_pjsip]
endpoint = memory_cache,ps_endpoints,maximum_objects=5000,object_lifetime_stale=60
endpoint = realtime,ps_endpoints
auth = memory_cache,ps_auths,maximum_objects=5000,object_lifetime_stale=300
auth = realtime,ps_auths
aor = memory_cache,ps_aors,maximum_objects=5000,object_lifetime_stale=60
aor = realtime,ps_aors
contact = realtime,ps_contacts
registration = realtime,ps_registrations
transport = config,pjsip.conf,1
