namespace: r55-platform

api:
  image:
    repository: 192.168.122.1:5050/asterisk-platform/api
    tag: "1.14.6"
  replicas: 2
  port: 5000
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCpuPercent: 70
  postgres:
    host: postgres-pooler.r55-data.svc.cluster.local
    port: 5432
    database: asterisk_platform
    user: platform
    passwordSecret: platform-pg-credentials
    passwordKey: password
  redis:
    host: redis-0.redis.r55-data.svc.cluster.local
    port: 6379
  jwt:
    issuer: r55-staging
    audience: r55-staging
    keySecret: jwt-signing-key
    keyField: key
  serviceKey: r55-staging-service-key-change-in-prod
  corsOrigins: "http://r55.local,http://api.r55.local"
  asterisk:
    ami:
      hostname: asterisk-sip.r55-asterisk.svc.cluster.local
      port: 5038
      username: platform
      password: r55-staging-only-change-prod
    ari:
      baseUrl: http://asterisk-ari.r55-asterisk.svc.cluster.local:8088
      username: asterisk-platform
      password: r55-staging-only-change-prod
      application: asterisk-platform
  licensing:
    enforcementMode: Disabled
  prometheus:
    enabled: false

web:
  image:
    repository: 192.168.122.1:5050/asterisk-platform/web
    tag: "1.15.5"
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingress:
  enabled: true
  hostnameApi: api.r55.local
  hostnameWeb: r55.local
  tlsEnabled: false
