apiVersion: v1
kind: Service
metadata:
  name: platform-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "platform.apiLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
