apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.postgres.passwordSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "platform.apiLabels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.api.postgres.user }}
  {{ .Values.api.postgres.passwordKey }}: r55-staging-only-change-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.jwt.keySecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "platform.apiLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.jwt.keyField }}: r55-staging-jwt-signing-key-min-32-chars-long
