<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Version>$(PackageVersion)</Version>
    <Description>Stateless PDF/CSV rendering microservice for Verbara.Platform</Description>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Verbara.Platform.Core\Verbara.Platform.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ScottPlot" />
  </ItemGroup>

</Project>
