using Verbara.Platform.Core;

namespace Verbara.Platform.Typification.Ai;

/// <summary>
/// Shadow record of every AI suggestion emitted by the typification classifier.
/// Persisted verbatim so later tasks can run shadow mode, derive provenance
/// server-side, and compute calibration accuracy via <see cref="IAiSuggestionStore.QueryAccuracyAsync"/>.
/// </summary>
public sealed class AiSuggestionRecord
{
    /// <summary>Opaque surrogate key (generated by the caller before insert).</summary>
    public required EntityId Id { get; init; }

    /// <summary>Tenant that owns this record.</summary>
    public required EntityId TenantId { get; init; }

    /// <summary>Conversation for which the suggestion was produced.</summary>
    public required EntityId ConversationId { get; init; }

    /// <summary>Schema used to generate the suggestion.</summary>
    public required EntityId SchemaId { get; init; }

    /// <summary>Exact schema version at suggestion time.</summary>
    public required int SchemaVersion { get; init; }

    /// <summary>The leaf node the AI selected.</summary>
    public required EntityId SuggestedLeafNodeId { get; init; }

    /// <summary>Full node path from root to leaf (serialized as JSONB).</summary>
    public required IReadOnlyList<string> SuggestedNodePath { get; init; }

    /// <summary>AI-suggested field values keyed by field key (serialized as JSONB).</summary>
    public required IReadOnlyDictionary<string, string> SuggestedFieldValues { get; init; }

    /// <summary>Self-reported confidence in [0, 1].</summary>
    public required double Confidence { get; init; }

    /// <summary>Optional free-form sentiment hint from the model.</summary>
    public string? Sentiment { get; init; }

    /// <summary>Model identifier (e.g. <c>gpt-4o-mini</c>).</summary>
    public required string ModelId { get; init; }

    /// <summary>Prompt template version used for this call.</summary>
    public required string PromptVersion { get; init; }

    /// <summary>
    /// The delivery band that was actually surfaced to the agent for this suggestion
    /// (<see cref="TypificationBand.None"/> for shadow / below-threshold /
    /// sentiment-gated). Persisted so calibration can EXCLUDE auto-filled samples — once a form
    /// is auto-filled the agent's "acceptance" is biased, so AutoFill-band rows must not count
    /// toward the gate that decides whether AutoFill stays on.
    /// </summary>
    public required TypificationBand SurfacedBand { get; init; }

    /// <summary>UTC timestamp when the suggestion was generated.</summary>
    public required DateTimeOffset CreatedAt { get; init; }

    // ── Reconciliation fields (set via MarkReconciledAsync) ─────────────────

    /// <summary>
    /// The leaf node actually committed by the agent. <see langword="null"/> until reconciled.
    /// </summary>
    public EntityId? CommittedLeafNodeId { get; init; }

    /// <summary>
    /// Whether the agent accepted the AI suggestion.
    /// <see langword="null"/> until reconciled.
    /// </summary>
    public bool? Accepted { get; init; }
}
