[modules]
autoload = yes
noload = chan_sip.so
noload = chan_skinny.so
noload = chan_mgcp.so
noload = cdr_pgsql.so
noload = cel_pgsql.so
noload = res_config_pgsql.so
noload = res_odbc.so
noload = res_config_odbc.so
