apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: asterisk
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "asterisk.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asterisk
