apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.asterisk.postgres.passwordSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.asterisk.postgres.user }}
  {{ .Values.asterisk.postgres.passwordKey }}: r55-staging-only-change-prod
