[settings]
ps_endpoints => pgsql,general,ps_endpoints
ps_auths => pgsql,general,ps_auths
ps_aors => pgsql,general,ps_aors
ps_contacts => pgsql,general,ps_contacts
ps_registrations => pgsql,general,ps_registrations
queues => pgsql,general,rt_queues
queue_members => pgsql,general,rt_queue_members
