[res_pjsip]
endpoint = realtime,ps_endpoints
auth = realtime,ps_auths
aor = realtime,ps_aors
contact = realtime,ps_contacts
registration = realtime,ps_registrations
transport = config,pjsip.conf,1

[res_pjsip_endpoint_identifier_ip]
identify = realtime,ps_endpoint_id_ips
