using System.Runtime.CompilerServices;

namespace Verbara.Platform.Architecture.Tests;

/// <summary>
/// Locates the repo's <c>src/</c> tree (anchored off this file's compile-time path so it works
/// regardless of the working directory or CI layout) and enumerates the real endpoint source files,
/// excluding build output and generated code. Mirrors the Governance.Tests <c>TestTreeSource</c>
/// walk-to-slnx technique, but returns the <c>src/</c> root and filters to <c>Endpoints/</c> files.
/// </summary>
internal static class SourceTreeSource
{
    private const string SolutionFile = "Verbara.Platform.slnx";

    private static readonly string[] GeneratedSuffixes =
    [
        ".g.cs",
        ".Designer.cs",
        ".generated.cs",
    ];

    /// <summary>
    /// Walks parent directories from <paramref name="callerPath"/> until it finds the repo root
    /// (the directory containing <c>Verbara.Platform.slnx</c>) and returns its <c>src/</c> folder.
    /// Throws if the root cannot be located, so a path regression fails loudly instead of silently
    /// scanning nothing.
    /// </summary>
    public static string SrcRoot([CallerFilePath] string callerPath = "")
    {
        var dir = Directory.GetParent(callerPath);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, SolutionFile)))
                return Path.Combine(dir.FullName, "src");

            dir = dir.Parent;
        }

        throw new InvalidOperationException(
            $"Could not locate '{SolutionFile}' walking up from '{callerPath}'. " +
            "The architecture guard cannot find the repo's src/ tree.");
    }

    /// <summary>Repo root — the directory that contains <c>Verbara.Platform.slnx</c>.</summary>
    public static string RepoRoot() => Directory.GetParent(SrcRoot())!.FullName;

    /// <summary>
    /// Enumerates every real endpoint source file: any <c>*.cs</c> under a directory segment named
    /// <c>Endpoints</c> beneath <see cref="SrcRoot"/>, excluding <c>obj</c>/<c>bin</c> segments,
    /// generated filenames, and files carrying an <c>&lt;auto-generated</c> banner in their first 3 lines.
    /// </summary>
    public static IEnumerable<string> EnumerateEndpointSources()
    {
        var root = SrcRoot();
        foreach (var file in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
        {
            if (!HasSegment(file, "Endpoints"))
                continue;
            if (HasExcludedSegment(file))
                continue;
            if (HasGeneratedSuffix(file))
                continue;
            if (LooksAutoGenerated(file))
                continue;

            yield return file;
        }
    }

    private static bool HasSegment(string path, string segmentName)
    {
        foreach (var segment in path.Split(Path.DirectorySeparatorChar))
        {
            if (segment == segmentName)
                return true;
        }

        return false;
    }

    private static bool HasExcludedSegment(string path)
    {
        foreach (var segment in path.Split(Path.DirectorySeparatorChar))
        {
            if (segment is "obj" or "bin")
                return true;
        }

        return false;
    }

    private static bool HasGeneratedSuffix(string path)
    {
        var fileName = Path.GetFileName(path);
        foreach (var suffix in GeneratedSuffixes)
        {
            if (fileName.EndsWith(suffix, StringComparison.Ordinal))
                return true;
        }

        return false;
    }

    private static bool LooksAutoGenerated(string path)
    {
        using var reader = new StreamReader(path);
        for (var i = 0; i < 3; i++)
        {
            var line = reader.ReadLine();
            if (line is null)
                break;
            if (line.Contains("<auto-generated", StringComparison.Ordinal))
                return true;
        }

        return false;
    }
}
